/**
 * The demo household: Margaret, 81, at home; Sarah, her daughter, 40 minutes
 * away; Tom, her grandson; Anna, a home aide on weekday mornings.
 *
 * Every name, photo, recording and event here is sample material. The history
 * is generated by the simulator and ends in a moderate sudden change, so the
 * morning digest of the demo day carries a Change Signal alert.
 */

import type { Household, MantelEvent, PlanItem, Topic } from "./model";
import { mulberry32, simulate } from "./sim";
import type { DayFeatures } from "./signal";
import { builtinTopics } from "./topics";
import { addDays, localParts, parseClock, weekdayOf, zonedInstant } from "./time";

export const DEMO_TZ = "America/New_York";

export function demoHousehold(now: Date): Household {
  const tz = DEMO_TZ;
  const today = localParts(now, tz).date;
  const at = (date: string, hhmm: string) => zonedInstant(date, hhmm, tz).toISOString();
  const minute = localParts(now, tz).minuteOfDay;
  const past = (hhmm: string, lag = 10) => parseClock(hhmm) + lag <= minute;

  const members = [
    { id: "sarah", name: "Sarah", relation: "your daughter", role: "primary" as const, photo: "photo-sarah", aliases: ["sally"] },
    { id: "tom", name: "Tom", relation: "your grandson", role: "family" as const, photo: "photo-tom", aliases: ["tommy"] },
    { id: "anna", name: "Anna", relation: "your helper", role: "aide" as const, photo: "photo-anna" },
  ];
  const settings = {
    timezone: tz,
    locale: "en-US",
    wake: "07:00",
    bedtime: "21:30",
    evening: { start: "16:30", end: "19:30" },
    listening: "questions" as const,
    visitWindowMinutes: 45,
    answerSeconds: 20,
    nightAlerts: { doorOpen: true, presence: false },
    homeLine: "on Maple Street",
  };

  const plan: PlanItem[] = [];
  const add = (date: string, time: string, kind: PlanItem["kind"], title: string, extra: Partial<PlanItem> = {}) =>
    plan.push({ id: `plan-${date}-${time.replace(":", "")}-${kind}`, date, time, kind, title, ...extra });

  for (let d = 0; d < 3; d++) {
    const date = addDays(today, d);
    const weekday = weekdayOf(date);
    const aideDay = weekday >= 1 && weekday <= 5;
    const isToday = d === 0;
    add(date, "08:30", "meal", "Breakfast", isToday && past("08:30") ? { doneAt: at(date, "08:41"), doneBy: aideDay ? "anna" : "sarah" } : {});
    if (aideDay) add(date, "09:00", "visit", "Anna is coming", { who: "anna", ...(isToday && past("09:00") ? { doneAt: at(date, "09:02"), doneBy: "anna" } : {}) });
    add(date, "09:15", "pills", "Morning pills", isToday && past("09:15") ? { doneAt: at(date, "09:14"), doneBy: aideDay ? "anna" : "sarah" } : {});
    add(date, "12:30", "meal", "Lunch", isToday && past("12:30", 25) ? { doneAt: at(date, "12:52"), doneBy: aideDay ? "anna" : "sarah" } : {});
    if (d === 0) add(date, "16:00", "visit", "Sarah is coming", { who: "sarah" });
    add(date, "18:00", "meal", "Dinner");
    if (d === 1) add(date, "11:00", "visit", "Tom is coming", { who: "tom" });
    if (d === 2) add(date, "10:00", "delivery", "A parcel from the pharmacy", { until: "13:00" });
  }

  const written = at(addDays(today, -3), "19:20");
  const approved = { approvedBy: "sarah", approvedAt: written };
  const sarah = members[0]!;
  const topics: Topic[] = builtinTopics({ members, settings }, sarah, written).map((t) => ({ ...t, ...approved }));
  const where = topics.find((t) => t.builtin === "where");
  if (where) where.answer = "You're at home, on Maple Street. You've lived here since 1974. You're safe.";

  topics.push(
    {
      id: "topic-robert",
      label: "Robert",
      phrasings: ["where is robert", "when is robert coming home", "is robert at work", "where is my husband", "has robert called", "i want to see robert", "is bob home yet"],
      entities: ["other:robert"],
      statements: true,
      policy: "redirect",
      answer: "Robert loved this house. Shall we look at your photos from Lake Tahoe?",
      audio: "audio-robert-sarah",
      photo: "moment-tahoe-1968",
      fallback: "Robert loved you very much.",
      author: "sarah",
      updatedAt: written,
      ...approved,
    },
    {
      id: "topic-biscuit",
      label: "Biscuit the dog",
      phrasings: ["is the dog fed", "where is biscuit", "has the dog eaten", "did i feed the dog", "where is the dog", "i need to feed biscuit"],
      entities: ["other:biscuit"],
      statements: true,
      policy: "tell",
      answer: "Biscuit lives with Sarah now. He's happy and well fed, and he visits on Sundays.",
      photo: "moment-biscuit-2015",
      fallback: "Biscuit is happy and well fed.",
      author: "sarah",
      updatedAt: written,
      ...approved,
    },
    {
      id: "topic-purse",
      label: "My purse",
      phrasings: ["where is my purse", "i can not find my purse", "where did i put my purse", "has someone taken my purse", "where is my handbag"],
      statements: true,
      policy: "tell",
      answer: "Your purse is in the top drawer of the hall table.",
      fallback: "Your purse is safe in the house.",
      author: "sarah",
      updatedAt: written,
      ...approved,
    },
    {
      id: "topic-bills",
      label: "Bills and money",
      phrasings: ["have i paid the bills", "do i need to pay the bills", "is the electric bill paid", "do i have enough money", "who pays the bills"],
      policy: "tell",
      answer: "Sarah takes care of the bills. Everything is paid.",
      fallback: "The bills are taken care of.",
      author: "sarah",
      updatedAt: written,
      ...approved,
    },
  );

  const moments = [
    { id: "m-tahoe", photo: "moment-tahoe-1968", caption: "You and Robert at Lake Tahoe, 1968.", year: "1968", people: ["Robert"], calm: true,
      story: { text: "You wouldn't get out of the water all afternoon, and Robert fell asleep on the dock.", audio: "audio-story-tahoe-sarah", by: "sarah" } },
    { id: "m-wedding", photo: "moment-wedding-1965", caption: "Your wedding day, June 1965.", year: "1965", people: ["Robert"], calm: true },
    { id: "m-graduation", photo: "moment-graduation-1994", caption: "Sarah's graduation, 1994. You drove all night to be there.", year: "1994", people: ["Sarah"], calm: true },
    { id: "m-biscuit", photo: "moment-biscuit-2015", caption: "Biscuit as a puppy, 2015.", year: "2015", people: [], calm: true },
    { id: "m-roses", photo: "moment-roses", caption: "Your roses by the back porch.", people: [], calm: true },
  ].map((m) => ({ ...m, uploadedBy: "sarah", approvedBy: "sarah", approvedAt: written }));
  moments.push({
    id: "m-birthday",
    photo: "moment-birthday-2004",
    caption: "Tom's first birthday, 2004.",
    year: "2004",
    people: ["Tom"],
    calm: false,
    uploadedBy: "tom",
  } as (typeof moments)[number]);

  return {
    id: "hale",
    name: "Margaret's home",
    person: {
      name: "Margaret",
      others: [
        { name: "Robert", relation: "your husband", aliases: ["bob", "bobby"], photo: "photo-robert" },
        { name: "Biscuit", relation: "your dog" },
      ],
    },
    members,
    settings,
    plan,
    topics,
    moments,
    messages: [
      {
        id: "msg-morning",
        from: "sarah",
        media: "audio-msg-morning-sarah",
        mediaKind: "audio",
        text: "Good morning, Mum. It's a lovely day. I'll see you at four o'clock.",
        schedule: { kind: "first-seen-after", date: today, time: "07:00" },
        approvedBy: "sarah",
        approvedAt: at(today, "06:40"),
      },
      {
        id: "msg-evening",
        from: "tom",
        media: "audio-msg-evening-tom",
        mediaKind: "audio",
        text: "Hi Grandma, it's Tom. I'm coming to see you tomorrow at eleven. Sleep well.",
        schedule: { kind: "evening-end", date: today },
        approvedBy: "sarah",
        approvedAt: at(today, "06:45"),
      },
    ],
    unusualDays: [],
  };
}

const UNKNOWN_SAMPLES = ["is it going to rain", "did the paper come", "where are my glasses", "is my mother coming"];

/**
 * Turn simulated care-day features into the raw events a TV would have sent,
 * so the server's digest and signal run on the same path as in production.
 */
export function eventsFromFeatures(h: Household, days: DayFeatures[], seed = 7): MantelEvent[] {
  const tz = h.settings.timezone;
  const rnd = mulberry32(seed);
  const pick = <T>(xs: T[]) => xs[Math.floor(rnd() * xs.length)]!;
  const events: MantelEvent[] = [];
  let n = 0;
  const push = (atMs: number, type: MantelEvent["type"], data?: Record<string, unknown>) =>
    events.push({ id: `sim-${++n}`, at: new Date(atMs).toISOString(), type, ...(data ? { data } : {}) });
  const weighted = h.topics.filter((t) => t.approvedBy);
  const weights = weighted.map((t) => (t.id === "builtin-day" ? 5 : t.builtin === "visit-of" ? 4 : t.id === "topic-robert" ? 4 : t.builtin === "time" ? 3 : 1));
  const total = weights.reduce((a, b) => a + b, 0);
  const topicPick = () => {
    let r = rnd() * total;
    for (let i = 0; i < weighted.length; i++) {
      r -= weights[i]!;
      if (r <= 0) return weighted[i]!;
    }
    return weighted[0]!;
  };

  for (const d of days) {
    const wake = zonedInstant(d.date, h.settings.wake, tz).getTime();
    const bed = zonedInstant(d.date, h.settings.bedtime, tz).getTime();
    if (d.firstSeen !== null) {
      // Three sessions in front of the TV: morning, afternoon, evening.
      const first = wake + d.firstSeen * 60_000;
      const sessions: [number, number][] = [
        [first, first + (100 + rnd() * 60) * 60_000],
        [zonedInstant(d.date, "13:10", tz).getTime() + rnd() * 30 * 60_000, zonedInstant(d.date, "15:40", tz).getTime()],
        [zonedInstant(d.date, "16:20", tz).getTime(), bed - (10 + rnd() * 40) * 60_000],
      ];
      for (const [a, b] of sessions) {
        if (b <= a) continue;
        push(a, "presence.start");
        push(b, "presence.end");
      }
      const qs = d.questions ?? 0;
      for (let i = 0; i < qs; i++) {
        const [a, b] = pick(sessions);
        const t = a + rnd() * Math.max(1, b - a);
        if (rnd() < 0.08) push(t, "question", { text: pick(UNKNOWN_SAMPLES), topicId: null, score: 0.2 });
        else {
          const topic = topicPick();
          push(t, "question", { text: topic.phrasings[0], topicId: topic.id, score: 0.9 });
        }
      }
      const shown = 6 + Math.floor(rnd() * 10);
      for (let i = 0; i < shown; i++) {
        const [a, b] = pick(sessions);
        push(a + rnd() * Math.max(1, b - a), "moment.shown", { id: pick(h.moments).id });
      }
    }
    if (d.nightMinutes) {
      const start = zonedInstant(addDays(d.date, 1), "00:10", tz).getTime() + rnd() * 20 * 60_000;
      push(start, "presence.start");
      push(start + d.nightMinutes * 60_000, "presence.end");
    }
    for (let i = 0; i < (d.nightDoorOpens ?? 0); i++) {
      const t = zonedInstant(addDays(d.date, 1), "03:05", tz).getTime() + i * 5 * 60_000;
      push(t, "contact.open", { sensor: "Front door" });
      push(t + 90_000, "contact.close", { sensor: "Front door" });
    }
  }
  return events.sort((a, b) => a.at.localeCompare(b.at));
}

/**
 * Forty care days ending yesterday, with a strong sudden change that started
 * the day before yesterday: the story the demo's Change Signal alert tells.
 * Seed 7 is the one whose alert lands on yesterday itself, which is the
 * morning the film shows.
 */
export function demoHistory(h: Household, now: Date): { days: DayFeatures[]; events: MantelEvent[] } {
  const today = localParts(now, h.settings.timezone).date;
  const nDays = 40;
  const tape = simulate(7, {
    days: nDays,
    startDate: addDays(today, -nDays),
    intensity: "strong",
    onset: nDays - 2,
    ramp: 1,
    series: { questions: true, night: true, firstSeen: true },
  });
  return { days: tape.days, events: eventsFromFeatures(h, tape.days) };
}
